### ISSUE TITLE
TSSC Button: Sonarqube

### ISSUE THREAD

**Issue by jflowers** [ploigos/ploigos-software-factory-operator#10]
### Summary
---
This operator should coordinate with the sonarqube-operator to deploy and configure a sonarqube instance to meet the needs of this operatos 3 CRDs: TsscPlatform, TsscWorkshop, and TsscApp

### Linked Issues
---
- [ ] [TSSC: Sonarqube - Move Tasks to Operator](https://github.com/RedHatGov/tssc-operator/issues/64)
- [ ] [CRD for plugins](https://github.com/RedHatGov/sonarqube-operator/issues/14)
- [ ] [Use dedicated service account](https://github.com/RedHatGov/sonarqube-operator/issues/15)
- [ ] [Convert to osdk-wrapper workflow](https://github.com/RedHatGov/sonarqube-operator/issues/16)
- [ ] [Provide SonarQube version 8.n](https://github.com/RedHatGov/sonarqube-image/issues/3)

TODO:
Make issues for:

- Follow up with Peggy to address gaps, note the following link is not complete: https://github.com/rhtconsulting/tssc-infra/blob/master/docs/sonarqube/tssc_admin.adoc
