### ISSUE TITLE
TSSC Button: Mattermost

### ISSUE THREAD

**Issue by jflowers** [ploigos/ploigos-software-factory-operator#11]
### Summary
---
This operator should coordinate with the mattermost-operator to deploy and configure a mattermost instance to meet the needs of this operator 3 CRDs: TsscPlatform, TsscWorkshop, and TsscApp

### Linked Issues
---

- [ ] [TSSC: Mattermost - Move Tasks to Operator](https://github.com/RedHatGov/tssc-operator/issues/65)
- [ ] [Use dedicated service account](https://github.com/RedHatGov/mattermost-operator/issues/1)
- [ ] [Identify and correct antipatterns in  operator](https://github.com/RedHatGov/mattermost-operator/issues/2)
- [ ] [Convert to osdk-wrapper workflow](https://github.com/RedHatGov/mattermost-operator/issues/3)
