### ISSUE TITLE
TSSC Button: Quay

### ISSUE THREAD

**Issue by jflowers** [ploigos/ploigos-software-factory-operator#16]
### Summary
---
This operator should coordinate with the quay-operator to deploy and configure a quay instance to meet the needs of this operatos 3 CRDs: TsscPlatform, TsscWorkshop, and TsscApp

### Linked Issues
---

- [ ] [Quay Configuration (org,accounts,etc) need managed by TSSC operator](https://github.com/RedHatGov/tssc-operator/issues/43)
- [ ] [TSSC Images need imported  by TSSC operator](https://github.com/RedHatGov/tssc-operator/issues/44)
- [ ] [Quay lookup passwords should be put in secrets](https://github.com/RedHatGov/tssc-operator/issues/23)
